'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { getSupabaseBrowserClient } from '@/lib/supabase/browser';

const input = 'w-full rounded-xl border border-white/10 bg-white/[.05] px-4 py-3 text-sm text-white placeholder-white/35 outline-none focus:border-blue-400/60';

export default function AuthForm({ mode }) {
  const router = useRouter(); const [form, setForm] = useState({ name: '', email: '', password: '', confirm: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setMessage(''); if (mode === 'signup' && form.password !== form.confirm) return setMessage('Passwords do not match.'); setBusy(true); try { const supabase = getSupabaseBrowserClient(); let result; if (mode === 'login') result = await supabase.auth.signInWithPassword({ email: form.email, password: form.password }); else if (mode === 'signup') { const response = await fetch('/api/auth/me', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.name, email: form.email, password: form.password }) }); const data = await response.json(); if (!response.ok) result = { error: { message: data.error } }; else { setMessage(data.needsEmailConfirmation ? 'Check your email to confirm your account.' : 'Account created.'); router.push(data.needsEmailConfirmation ? '/login' : '/account'); return; } } else result = await supabase.auth.resetPasswordForEmail(form.email, { redirectTo: `${window.location.origin}/reset-password` }); if (result?.error) setMessage(result.error.message); else if (mode === 'login') { const next = new URLSearchParams(window.location.search).get('next'); const profileResponse = await fetch('/api/auth/me'); const profileData = await profileResponse.json(); router.push(next?.startsWith('/') ? next : profileData.user?.role === 'admin' ? '/admin' : '/account'); } else setMessage('Check your email for the next step.'); } catch { setMessage('Supabase is not configured yet. Add the Phase 2 environment variables.'); } finally { setBusy(false); } };
  const title = mode === 'login' ? 'Welcome back' : mode === 'signup' ? 'Create your account' : 'Reset your password';
  return <div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#080b12]/80 p-6 shadow-2xl backdrop-blur-xl sm:p-8"><p className="mb-2 font-mono text-[10px] uppercase tracking-[.25em] text-blue-300/70">DavinciWaleBhaiya / Account</p><h1 className="mb-7 text-3xl font-semibold tracking-tight text-white">{title}</h1><form onSubmit={submit} className="space-y-4">{mode === 'signup' && <input required className={input} placeholder="Name" value={form.name} onChange={(e) => set('name', e.target.value)} />}<input required type="email" className={input} placeholder="Email" value={form.email} onChange={(e) => set('email', e.target.value)} />{mode !== 'forgot' && <input required minLength={8} type="password" className={input} placeholder="Password" value={form.password} onChange={(e) => set('password', e.target.value)} />}{mode === 'signup' && <input required minLength={8} type="password" className={input} placeholder="Confirm password" value={form.confirm} onChange={(e) => set('confirm', e.target.value)} />}<button disabled={busy} className="w-full rounded-xl bg-white px-4 py-3 text-sm font-medium text-black disabled:opacity-50">{busy ? 'Please wait…' : mode === 'login' ? 'Login' : mode === 'signup' ? 'Create account' : 'Send reset link'}</button></form>{message && <p className="mt-4 text-xs text-amber-300">{message}</p>}<div className="mt-6 space-y-2 text-center text-xs text-white/50">{mode === 'login' && <><a className="block hover:text-white" href="/forgot-password">Forgot password?</a><a className="block hover:text-white" href="/signup">Create account</a></>}{mode === 'signup' && <a className="block hover:text-white" href="/login">Already have an account? Login</a>}{mode === 'forgot' && <a className="block hover:text-white" href="/login">Back to login</a>}</div></div>;
}
