'use client';

import { useEffect, useState } from 'react';
import { getSupabaseBrowserClient } from '@/lib/supabase/browser';

export default function AccountPanel() {
  const [user, setUser] = useState(null); const [products, setProducts] = useState([]); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/auth/me').then((r) => r.json()).then((d) => { if (!d.user) window.location.href = '/login'; else setUser(d.user); }); fetch('/api/account/library').then(async (r) => { const d = await r.json(); if (r.ok) setProducts(d.products || []); else setMessage(d.error); }); }, []);
  const logout = async () => { await getSupabaseBrowserClient().auth.signOut(); window.location.href = '/'; };
  const download = async (id) => { setMessage('Preparing secure download…'); const r = await fetch(`/api/products/${id}/download`, { method: 'POST' }); const d = await r.json(); if (!r.ok) return setMessage(d.error || 'Download unavailable'); window.location.href = d.url; setMessage('Download started.'); };
  return <><div className="mb-10 flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-6"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-blue-300/70">Customer account</p><h1 className="mt-2 text-3xl font-semibold">{user?.name || 'Your library'}</h1><p className="mt-1 text-sm text-white/50">{user?.email}</p></div><div className="flex gap-3 text-xs"><a className="rounded-full border border-white/10 px-4 py-2 hover:border-white/30" href="/">Back to site</a><button onClick={logout} className="rounded-full bg-white px-4 py-2 text-black">Logout</button></div></div><h2 className="mb-4 text-lg">My library</h2>{message && <p className="mb-4 text-xs text-amber-300">{message}</p>}{products.length === 0 ? <div className="rounded-2xl border border-white/10 p-10 text-center text-sm text-white/50">Your downloaded assets will appear here.</div> : <div className="grid gap-4 md:grid-cols-2">{products.map((product) => <article key={product.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-white/40">{product.category} · v{product.version}</p><h3 className="mt-2 text-lg font-medium">{product.name}</h3></div><span className="text-[10px] text-emerald-300">{product.accessType}</span></div><div className="flex items-center justify-between text-xs text-white/45"><span>{product.lastDownloadAt ? `Last download ${new Date(product.lastDownloadAt).toLocaleDateString()}` : 'Ready to download'}</span><button onClick={() => download(product.id)} className="rounded-lg bg-white px-3 py-2 font-medium text-black">Download</button></div></article>)}</div>}</>;
}
